### ISSUE TITLE
Create OAuth credentials

### ISSUE THREAD

**Issue by sthrs** [robincsamuel/ghost-google-drive#1]
Hi,

I'm trying to follow the steps, but I'm afraid the steps are different now. I'm confused. Would you mind take a look at google dev console, see if I was correct or false?

**Comment by alexzaitsev** [comment]
@svw hi, you can check my [pull request](https://github.com/robincsamuel/ghost-google-drive/pull/3) for latest screenshots

**Comment by robincsamuel** [comment]
Thanks @alexzaitsev! Merged.
