### ISSUE TITLE
502 Proxy Error - if insert the post image (feature_image) from computer

### ISSUE THREAD

**Issue by wuulala** [robincsamuel/ghost-google-drive#11]
if insert the post image (feature_image) from computer, failed to open the post.

> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /mimaru-ueno-north/.
> Reason: Error reading from remote server

My post:
https://blog.wuulala.com/mimaru-ueno-north/

feature_image:
https://blog.wuulala.com/content/images/x1m0aELJxKJA44oKCTDmNhUSTIGAEA26oS.jpg.pagespeed.ic.h9_ZHsvDhW.webp

the generated html
```
<a href="/mimaru-ueno-north/" class="js-fadein c-post-card__image is-inview" style="background-image:url(/content/images/x1m0aELJxKJA44oKCTDmNhUSTIGAEA26oS.jpg.pagespeed.ic.h9_ZHsvDhW.webp)" aria-label="MIMARU 上野北" aria-hidden="true" role="presentation" tabindex="-1"></a>
```

**Comment by robincsamuel** [comment]
The image url seems wrong. It should end at `.jpg`. Can you try with the latest version please?
