### ISSUE TITLE
Ghost Google Drive API : Config File is not valid JSON

### ISSUE THREAD

**Issue by godgoali** [robincsamuel/ghost-google-drive#15]
this correct file :+1: 

Original from tutorial =

"storage": {
  "active": "ghost-google-drive",
  "ghost-google-drive": {
    "key": {
            "private_key_id": "YOUR PRIVATE KEY ID",
            "private_key": "YOUR PRIVATE KEY",
            "client_email": "YOUR CLIENT EMAIL",
            "client_id": "YOUR CLIENT ID",
     }
  }
},

Fix = 

 "storage": {
    "active": "ghost-google-drive",
    "ghost-google-drive": {
      "key": {
            "private_key_id": "YOUR PRIVATE KEY ID",
            "private_key": "YOUR PRIVATE KEY",
            "client_email": "YOUR CLIENT EMAIL",
            "client_id": "YOUR CLIENT ID"
    }
   }
  },

Missing symbol ( , ) from "client_id": "YOUR CLIENT ID"

**Comment by robincsamuel** [comment]
Thanks for the PR #16. It's merged.
