### ISSUE TITLE
404 When attempting to save image 

### ISSUE THREAD

**Issue by behoyh** [robincsamuel/ghost-google-drive#20]
Hi,

I attempted to follow your instructions the best I could with installation.

This package is being used in the docker file at [https://github.com/behoyh/ghost](https://github.com/behoyh/ghost ), but I am getting the following error after saving an image:

`Error: Request failed with status code 404 at createError (/ghost/content/adapters/storage/ghost-google-drive/node_modules/axios/lib/core/createError.js:16:15) at settle (/ghost/content/adapters/storage/ghost-google-drive/node_modules/axios/lib/core/settle.js:18:12) at Unzip.handleStreamEnd (/ghost/content/adapters/storage/ghost-google-drive/node_modules/axios/lib/adapters/http.js:201:11) at Unzip.emit (events.js:187:15) at endReadableNT (_stream_readable.js:1094:12) at process._tickCallback (internal/process/next_tick.js:63:19)`

The app is running on Google Cloud Run.

Thanks in advance for your help!

**Comment by robincsamuel** [comment]
Could you please provide the version information?

**Comment by behoyh** [comment]
I got this to work by configuring the service account correctly. I apologize for not closing this sooner.
