### ISSUE TITLE
Images not uploading, but API request returns 200

### ISSUE THREAD

**Issue by mattguide** [robincsamuel/ghost-google-drive#21]
I have installed the adapter on my local Ghost instance, obtained the proper API configuration from console.cloud.google.com and loaded into config.production.json, and tested a few images. However, two issues I am seeing:

1.  My images are not uploading to the GDrive but are being stored locally. However, I can see the API requests on the Google Console for methods drive.files.get and drive.files.insert with response code 200. The images appear to be getting hashed names, but they are going into my local content/images/ folder (e.g. 192.168.1.106:2368/content/images/17RDvT9swQJ0ixLu3aDM0BdJYsJD4CNbb.jpg) and not content/images/YYYY/MM like the base storage adapter normally does–that makes me thing the ghost-google-drive adapter is doing something. Is this indeed processing on via Google APIs then storing locally? I cannot find the files on the GDrive, which is my next Q…
 2.  Where can I view these images if they have uploaded to the google drive? I cannot see any files in my personal GDrive associated with the cloud.google login (though they may not be uploading). This is the only Google Drive I can find, is it the correct one? If it is the right one, is it safe to assume the files are indeed not uploading despite seeing the API requests from above?

What are some next steps I can use to debug or test what’s happening here? Am I missing something? Would I be able to provide anything else here to help resolve this?

Thank you!

**Comment by ahmednabil950** [comment]
Please you should consider this issue and solve it asap

I have the same issue and it seems it is being downloaded it in `/content` dir even though it return 404 

Thanks in Advance

**Comment by robincsamuel** [comment]
Sorry, I couldn't find some time for this yet. 

@mattguide What version of Ghost you're using?

And about the visibility of files, it's uploaded to the service account and will not show up in your google drive. Some details [here](https://stackoverflow.com/questions/23382342/google-drive-access-for-service-account).

**Comment by mattguide** [comment]
@robincsamuel - I was using the last version before Ghost 3.x was released, so I think it was 2.11.x?  Sorry, I should have recorded the version, it was the latest at the time of posting in October.

That SO note is interesting... I do not completely follow what the "service account" is, but I will see if I can find those images somewhere.  

I have since moved to the cloudinary storage adapter, which worked like a charm.  However, I am willing to dig in a bit more here to get this working.

> 
> @mattguide What version of Ghost you're using?
> 
> And about the visibility of files, it's uploaded to the service account and will not show up in your google drive. Some details [here](https://stackoverflow.com/questions/23382342/google-drive-access-for-service-account).

**Comment by robincsamuel** [comment]
@mattguide If you followed the instructions to create a google console project, there is a service account creation. So the google authorization you use is of a service account, and the files you upload via that account will not be visible in your Gmail accounts google drive.

And yeah, if you could get some more information, I can try to fix this asap.

**Comment by robincsamuel** [comment]
I'm closing this issue since no response. Feel free to re-open if you are still facing the issue.
