### ISSUE TITLE
Not working with ghost 3.7.0?

### ISSUE THREAD

**Issue by gurenovich** [robincsamuel/ghost-google-drive#22]
I did steps from README and can't upload to Google Drive.

Log:
[2020-02-22 11:51:15] INFO "GET /content/images/1QtdKs9v4P3bknJnKxx_ovNeigTlwSukt.jpeg" 403 6323ms

How I can start ghost in dev mode? I want debug ghost google drive index file. Thanks for your repo!

**Comment by robincsamuel** [comment]
@gurenovich It seems like a problem with google API and not with the ghost. [Here is a reference](https://stackoverflow.com/questions/60284158/google-drive-api-were-sorry-but-your-computer-or-network-may-be-sending).

I think you can set the environment using `NODE_ENV`. Details [here](https://ghost.org/docs/concepts/config/)

I'll try to find some time this week to check this, but It'd be great if you can debug and share your findings. :)

**Comment by robincsamuel** [comment]
#23

**Comment by robincsamuel** [comment]
I've published a fix `2.0.3`, but that will only work for future ones as the update is related to setting the file permissions.

**Comment by gurenovich** [comment]
> I've published a fix `2.0.3`, but that will only work for future ones as the update is related to setting the file permissions.

Thanks, but it's not working yet.

I did as say README.

My config.development.json:
`"storage": {
    "active": "ghost-google-drive",
    "ghost-google-drive": {
      "key": {
        "private_key_id": "ba1f38...,
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhk...",
        "client_email": "ghost-27@gat...",
        "client_id": "109177..."
      }
    }
  }`

I got 201 status and link to image http://localhost:2368/content/images/1VIW51-Ypmj9wNWGAeK-S8XUW0pkvLB_u.png instead google drive link image.

I updated ghost to 3.8.0 and you library with fix

**Comment by robincsamuel** [comment]
Did you try to access the file that was uploaded earlier or a newly uploaded (after this library update) image?

**Comment by gurenovich** [comment]
> Did you try to access the file that was uploaded earlier or a newly uploaded (after this library update) image?

Newly uploaded. Can you make example repo, please? I so want to work with google drive in my blog

**Comment by robincsamuel** [comment]
@gurenovich I mean, create a new post, upload an image and then check if that image is showing up. Your existing posts may not work even with this update as noted [here](https://github.com/robincsamuel/ghost-google-drive/releases/tag/2.0.3)

**Comment by gurenovich** [comment]
@robincsamuel It's work for new posts!
But how it's work? I didn't see my newly images in google drive?

And it's not working with .png images => ghost to stop when I uploaded png.
Can you check it please and thank you for your best work!

**Comment by robincsamuel** [comment]
@gurenovich You won't see the uploads in your google drive. You are using a service account and it goes to the drive of that service account.

We are still working on that issue #25
