### ISSUE TITLE
Auto set permissions to connected google drive

### ISSUE THREAD

**Issue by behoyh** [robincsamuel/ghost-google-drive#25]
This is a follow-up item to #23, since now permissions need to be set on pre-2.0.3 uploaded files in order to view them.

Some issues to consider with setting everything in the directory to public:
- service account may be used with other apps, which has security implications.
- when does this run?
    - what happens when a failure occurs in the process?
- is there a CLI tool that we can direct users to use to migrate? eg. [gdrive](https://github.com/gdrive-org/gdrive)

**Comment by robincsamuel** [comment]
The simplest way is to direct to something like `gdrive`. I tried `gdrive` and it worked nicely, though I faced some issues to [make it work with a service account.](https://github.com/gdrive-org/gdrive/issues/242#issuecomment-277275201)

Here is the command I executed to update the permission of **ALL** the files. 

```
gdrive --service-account credentials.json list | while read line; do
    declare -a file=( $( echo $line | cut -d' ' -f1- ) );
    gdrive --service-account credentials.json share --discoverable ${file[1]};
done
```
However, I'm facing some kind of caching issue. The content url still returns `403`, unless I append a query string. And It's not my browser cache.

**Comment by robincsamuel** [comment]
Ah, sorry. I had Cloudflare caching turned on.

**Comment by robincsamuel** [comment]
@behoyh As you mentioned in the PR, I'm still getting `403` once in a while. Not sure if there is some throttling.

**Comment by robincsamuel** [comment]
How about trying the method mentioned [here](https://stackoverflow.com/a/60398478/1855383)?

Seems like those people faced the exact same issue.

**Comment by behoyh** [comment]
Just read the question and yeah, that would be ideal. I had no idea about that blog post! 

I can try testing the fix soon

**Comment by behoyh** [comment]
Permissions are set after uploading file #38
