### ISSUE TITLE
Where to view the images uploaded?

### ISSUE THREAD

**Issue by d0u9** [robincsamuel/ghost-google-drive#32]
Thanks for the great work. I uploaded a test image, and it works fine. But I cannot find this image in my google drive.

If I want to manage these data, how to do that?

**Comment by robincsamuel** [comment]
Hey,

You cannot see the images uploaded in your google drive, as the service account is a different one. Please see [this comment](https://github.com/robincsamuel/ghost-google-drive/issues/21#issuecomment-573515450)

**Comment by robincsamuel** [comment]
https://github.com/behoyh/google-drive-ui
