### ISSUE TITLE
How to view files that are uploaded by Ghost Blog

### ISSUE THREAD

**Issue by hexclann** [robincsamuel/ghost-google-drive#34]
The images are never deleted from the Ghost server once it is uploaded, previously I could go to `content/images` to view or modify the images. However the files stored in Google Drive is not viewed in G drive app because it is a service account. H ow can I view files that are uploaded to G drive?

[Similar question](https://stackoverflow.com/questions/14124946/google-drive-service-account-view-files-from-another-account)

**Comment by robincsamuel** [comment]
Hey,

As you said, there's no way to see that from google drive. The only option I see is to use APIs. However, deleting the image from the ghost admin should delete it from the drive.

I'm closing this as it's not an issue, please feel free to continue the discussion here.

**Comment by robincsamuel** [comment]
https://github.com/behoyh/google-drive-ui
