### ISSUE TITLE
Please correct the install instructions

### ISSUE THREAD

**Issue by ErisDS** [robincsamuel/ghost-google-drive#4]
Hi there!

I have just done a review of all the modules that have been linked [here](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module).

Your install instructions require users to do an `npm install --save` - this modifies the package.json and makes the upgrade path for Ghost much, much harder. This was never the intention with the storage system. 

Instead of `npm install --save`, please update your README and advise people to do the following:

`mkdir content/storage` (make the storage folder if it doesn't exist yet)
`cp node_modules/<module_name> content/storage/<module_name>` (copy the module into the right location)

That makes it much easier to upgrade Ghost in future. 

We are in the process of adding a cli tool that will do these steps automatically, so if your module isn't setup to work this way, it will need to be very soon 😉

**Comment by robincsamuel** [comment]
@ErisDS Could you please review the package installation again? I don't feel like the installation is neat, it'll be great if you could verify once.

**Comment by rahendatri** [comment]
@robincsamuel Hello, I tried to install the plugin by following the updated README based on this issue. However, `content/` belongs to `ghost` internal user and it is impossible to do `mkdir content/storage` as the admin user of Ghost. Plus, doing something like `sudo -u <admin ghost user> mkdir ...` looks like a dirty trick.
Can you give more details on the README regarding what user one should use to perform the installation steps ?
Thanks in advance.

**Comment by robincsamuel** [comment]
@rahendatri The instructions are not for an admin user. One should do this at the code level, and that's what Ghost asking to do. I agree the mkdir command is not very neat, but the note you see above is by the CTO of Ghost. 

I'm sorry I may not be able to update the Readme or installation steps as I didn't follow ghost updates for a while. I'd be happy to incorporate your inputs if you can share.
