### ISSUE TITLE
TypeError: [default.hbs] Path must be a string. Received undefined

### ISSUE THREAD

**Issue by sandrotonon** [robincsamuel/ghost-google-drive#8]
Hi i'm getting the following error when trying to run ghost with the ghost-google-drive storage.

`TypeError: [default.hbs] Path must be a string. Received undefined
     at assertPath (path.js:28:11)
     at Object.join (path.js:1251:7)
     at ghostGoogleDrive.read (/app/content/adapters/storage/ghost-google-drive/index.js:177:29)`

This is because "this.storagePath" is undefined in the index.js at line 177. But do you know how to fix this?

`this.storagePath = config.getContentPath('images');` does not work. It throws the error 
`TypeError: config.getContentPath is not a function`

**Comment by glur4k** [comment]
This is because "this.storagePath" is undefined in the index.js at line 177. But do you know how to fix this?
